255 report form save for user
ProspectOne/UserModule pull request #12
Opened 2017-09-21 19:33 UTC by Xapp73

2017-09-21 19:34 UTC, Xapp73 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Report form save for user](https://trello.com/c/yws2949H/255-report-form-save-for-user)

2017-09-28 22:40 UTC, Xapp73 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update UserModule and RBAC to use configurable user entity instead of hardcoded one. Then move user entity to the core.](https://trello.com/c/TtgMRzTG/298-update-usermodule-and-rbac-to-use-configurable-user-entity-instead-of-hardcoded-one-then-move-user-entity-to-the-core)

2017-10-02 09:55 UTC, HesyRa requested changes

2017-10-02 09:55 UTC, HesyRa commented on src/Controller/UserController.php
> +        $user = $this->entityManager->getRepository($this->userEntityClassName)
Use function `getUserById` from this class

2017-10-02 09:55 UTC, HesyRa commented on src/Controller/UserController.php
> +        $user = $this->entityManager->getRepository($this->userEntityClassName)
Use function `getUserById` from this class

2017-10-03 14:53 UTC, ikovalyov approved these changes

2017-10-04 12:42 UTC, merged