729-panel-performance
ProspectOne/UserModule pull request #30
Opened 2018-04-19 14:29 UTC by ikovalyov

2018-04-19 16:22 UTC, ikovalyov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Panel performance](https://trello.com/c/kzUYVMac/729-panel-performance)

2018-04-20 11:45 UTC, Xapp73 requested changes

2018-04-20 11:45 UTC, Xapp73 commented on src/Model/Factory/UserModelFactory.php
> +
remove EL plz

2018-04-20 11:45 UTC, Xapp73 commented on src/Model/UserModel.php
> +
2 ELs

2018-04-20 15:04 UTC, merged