User form is created by factory now.
ProspectOne/UserModule pull request #4
Opened 2017-07-19 14:10 UTC by ikovalyov

2017-07-21 12:41 UTC, ikovalyov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add user management system. Full information + API keys](https://trello.com/c/e9tG1LLH/15-add-user-management-system-full-information-api-keys)

2017-07-21 12:41 UTC, ikovalyov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add user management system. Full information + API keys](https://trello.com/c/e9tG1LLH/15-add-user-management-system-full-information-api-keys)

2017-07-21 13:09 UTC, HesyRa commented on src/Controller/Factory/UserControllerFactory.php
>  }
new line

2017-07-24 11:32 UTC, Xapp73 requested changes

2017-07-24 11:32 UTC, Xapp73 commented on src/Controller/Factory/UserControllerFactory.php
>  }
empty line plz if possible

2017-07-24 11:32 UTC, Xapp73 commented on src/Controller/UserController.php
> +     * @param $user
Correct annots plz (missing type)

2017-07-25 10:11 UTC, Xapp73 approved these changes

2017-07-25 10:19 UTC, HesyRa approved these changes

2017-07-26 18:13 UTC, HesyRa approved these changes

2017-07-31 11:32 UTC, Xapp73 approved these changes

2017-08-01 16:25 UTC, Xapp73 approved these changes

2017-08-01 16:25 UTC, Xapp73 commented on src/Controller/UserController.php
> +     * @return null|object
User?

2017-08-01 16:25 UTC, Xapp73 commented on src/Controller/UserController.php
> +     * @param $id
type?

2017-08-02 07:06 UTC, HesyRa approved these changes

2017-08-03 10:36 UTC, merged