Update user module
ProspectOne/UserModule pull request #8
Opened 2017-09-12 15:23 UTC by HesyRa

Fix error when edit current user and optimize module

2017-09-12 15:26 UTC, HesyRa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix edit current user email error](https://trello.com/c/VGm9VDco/240-fix-edit-current-user-email-error)

2017-09-12 17:33 UTC, Xapp73 approved these changes

2017-09-13 20:46 UTC, ikovalyov requested changes

2017-09-13 20:46 UTC, ikovalyov commented on src/Service/AuthAdapter.php
> +    public function getUserByToken(string $token) {
{ from new line in functions definitions here and later

2017-09-13 20:46 UTC, ikovalyov commented on src/Service/AuthAdapter.php
> +        return User::STATUS_RETIRED;
Why not use User::STATUS_RETIRED instead of this function?

2017-09-13 20:46 UTC, ikovalyov commented on src/Service/UserManager.php
>          if(in_array($user->getRoleName(),$roles, true)) {
return in_array($user->getRoleName(),$roles, true)

2017-09-13 20:49 UTC, HesyRa commented on src/Service/AuthAdapter.php
> +        return User::STATUS_RETIRED;
Для переопределения функции наследником.

2017-09-14 18:12 UTC, merged